version: "3"
services:
  worker:
    container_name: $API_NAME
    build:
      context: .
      args:
        # Build-time arguments
        - GIT_TOKEN=$GIT_TOKEN
    # deploy:
    #   resources:
    #     limits:
    #       cpus: 1.0 # 1 entire core dedicated.
    #       memory: 1024M
    #     reservations:
    #       memory: 512M
    env_file: .env
    networks:
      - internal-services

networks:
  internal-services:
    external: true
