name: CDK Diff Staging and Production

on:
  push:
    branch: [staging, master]
  pull_request:
    branch: [staging, master]

jobs:
  diffStacks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run CDK Diff
      uses: youyo/aws-cdk-github-actions@v1.1.10
      with:
        cdk_subcommand: 'diff'
        actions_comment: true
      env:
        GITHUB_TOKEN: ${{ secrets.CUSTOM_GIT_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Open Issue
      if: failure()
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.CUSTOM_GIT_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated issue for commit: ${{ github.sha }}",
          "body": "This issue was automatically created by GitHub Actions workflow **${{ github.workflow}}**. \n\n The commit hash was: _${{ github.sha }}_.",
          "assignees": ["${{ github.event.pull_request.user.login }}"]
          }'
